# Generated by Django 3.2 on 2024-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
