# Generated by Django 3.2 on 2024-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_useraccount_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HomeAndKitchen', 'HomeAndKitchen'), ('HealthAndCare', 'HealthAndCare'), ('Style', 'Style'), ('Digital', 'Digital'), ('Transformation', 'Transformation')], default='Transformation', max_length=14),
        ),
    ]
