# Generated by Django 3.2 on 2024-01-22 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(?:0|98|\\+98|\\+980|0098|098|00980)?(9\\d{9})$')]),
        ),
    ]
