# Generated by Django 3.2 on 2024-01-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HomeAndKitchen', 'HomeAndKitchen'), ('HealthAndCare', 'HealthAndCare'), ('Style', 'Style'), ('Digital', 'Digital'), ('Transformation', 'Transformation')], max_length=14),
        ),
    ]
